#!/usr/bin/perl

if($#ARGV!=1){
#usage
	print "Usage:\n $ARGV[0] filename classname\n\nFills out a default class with a header in the files filename.cpp \nand filename.hpp\n";
	die;
}
$infile=$ARGV[0];
$classname=$ARGV[1];

open (EP,">$infile.hpp");

print EP <<"HERE";
#ifndef ___${infile}_inc
#define ___${infile}_inc 1

#include"SDL_types.h"

class ${classname} {
    public:
        ${classname}(int bar);
        ~${classname}();

        int Foo(void);

    private:
    protected:
};

#endif
HERE

close(EP);

open (EP, ">$infile.cpp");
print EP <<"HERE";
#include "${infile}.hpp"
#include"globals.hpp"

${classname}::${classname}(int bar)
{
}

${classname}::~${classname}()
{
}

int ${classname}::Foo(void)
{
}

HERE

close EP;
